name: biggerview
version: '0.9'

services:
  web:
    image: biggerviewtest
    ports:
      - "3298:8080"
    environment:
      DB_HOST: db
      DB_USER: flaskuser
      DB_PASSWORD: deinpasswort
      DB_NAME: biggerview
      PYTHONUNBUFFERED: "1"
    # restart: unless-stopped
